name:             Newfangled Me
title:            Newfangled Me
description:      The incoherent musings of Alex Forey
logo:             site-logo.png
disqus_shortname: newfangledme
comments:         true
#Comment out url when working locally to resolve base urls correctly
#url:              http://your-website.com
markdown: redcarpet
pygments: true
timezone: Europe/London
future:   true
permalink: /:title

owner:
  name:           Alex Forey
  avatar:         http://gravatar.com/avatar/c757293cea100034c52c39bf7603918a?s=150
  email:          hello@alexforey.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        alexforey
  github:         alfo 
  stackexchange:  http://stackexchange.com/users/932591/alfo?tab=accounts
  instagram:      alexforey
  flickr:         alexforey

exclude: [Gemfile, Gemfile.lock]
include: [images]

sass:
    syntax: scss        # scss|sass
    style:  compact  # nested|expanded|compact|compressed